name: Deploy mkdocs to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.x'
      - run: cp CHANGELOG.md documentation/changelog.md
      - run: pip install mkdocs-material
      - run: mkdocs gh-deploy --force
